<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAi2zrx9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAi2zrx9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAi2zrx9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAi2zrx9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAi2zrx9\appProdProjectContainer([
    'container.build_hash' => 'Ai2zrx9',
    'container.build_id' => 'e59bac18',
    'container.build_time' => 1663337204,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAi2zrx9');
