<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRgppaka\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRgppaka/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRgppaka.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRgppaka\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRgppaka\appDevDebugProjectContainer([
    'container.build_hash' => 'Rgppaka',
    'container.build_id' => '489482c4',
    'container.build_time' => 1663353290,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRgppaka');
